### ISSUE TITLE
Remove Roles on Uninstall

### ISSUE THREAD

**Issue by hawkemediadev** [tributemedia/tcb_auth_client#19]
Have all TCB roles removed on uninstall.

**Comment by AntonioXIII** [comment]
Done, but need to follow up with Steve to see if he wants users created through TCB to be deleted as well.

**Comment by skenley** [comment]
I think we leave the users in place or at the very most make it an option
for the user uninstalling the module to choose to keep or delete the users.
I don't think you need to spend a bunch more time adding that, so leaving
it as is will be perfectly fine with me.

Steve Kenley
Senior Developer | Tribute Media
208.489.0062

**Comment by AntonioXIII** [comment]
Funny, was getting ready to text you about this! Thanks for the input, we'll leave users intact for now.
